# Generated by Django 5.2.6 on 2025-09-04 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Inning",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("runs", models.IntegerField(default=0)),
                ("wickets", models.IntegerField(default=0)),
                ("balls_played", models.IntegerField(default=0)),
                ("innings_order", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("match_code", models.CharField(max_length=10, unique=True)),
                (
                    "match_type",
                    models.CharField(
                        choices=[("single", "Single Player"), ("multi", "Multiplayer")],
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting", "Waiting for Player"),
                            ("ongoing", "Ongoing"),
                            ("completed", "Completed"),
                        ],
                        default="waiting",
                        max_length=20,
                    ),
                ),
                ("overs", models.IntegerField()),
                ("wickets", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=50, unique=True)),
                ("total_matches", models.IntegerField(default=0)),
                ("wins", models.IntegerField(default=0)),
                ("losses", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Ball",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("over_no", models.IntegerField()),
                ("ball_no", models.IntegerField()),
                ("bowler_choice", models.CharField(max_length=1)),
                ("batsman_choice", models.CharField(max_length=1)),
                (
                    "outcome",
                    models.CharField(
                        choices=[("runs", "Runs"), ("out", "Out")], max_length=10
                    ),
                ),
                ("runs_scored", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "inning",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="balls",
                        to="game.inning",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="inning",
            name="match",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="innings",
                to="game.match",
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="player1",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="matches_as_player1",
                to="game.player",
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="player2",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="matches_as_player2",
                to="game.player",
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="winner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="matches_won",
                to="game.player",
            ),
        ),
        migrations.AddField(
            model_name="inning",
            name="batting_player",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="innings_batted",
                to="game.player",
            ),
        ),
        migrations.AddField(
            model_name="inning",
            name="bowling_player",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="innings_bowled",
                to="game.player",
            ),
        ),
    ]
